### ISSUE TITLE
Should catch std::exception, not std::string

### ISSUE THREAD

**Issue by eudoxos** [mjbogusz/vl53l0x-linux#4]
Hi, just reading your code to learn (thanks!) I see you're catching std::string; I think that should be std::exception:

https://github.com/mjbogusz/vl53l0x-linux/blob/35a08de0ffd1a9f45ab7dbcd5b47bedbe85e8ba7/examples/continuousMultipleSensors.cpp#L74

**Comment by eudoxos** [comment]
Sorry, after looking at the rest of the code, I see it is correct. Closing :)

**Comment by mjbogusz** [comment]
In fact your initial thought was right, it should catch `std::exception`. But it should also throw one (for many reasons) and use `.what()` to extract the error message.

I've already fixed that in a project this library was developed for but I forgot to push these changes here.

**Comment by mjbogusz** [comment]
@eudoxos Can you please try the updated version (from master branch, no release tagged yet)? Tbh I don't have the sensors available for me right now so there's a possibility of a bug somewhere.

Besides the error handling other stuff has slightly changed too (mostly initialization, now it's only 1 method), so you may want to re-examine the updated examples.
