### ISSUE TITLE
Works with BeagleBone Blue too

### ISSUE THREAD

**Issue by usxbrix** [mjbogusz/vl53l0x-linux#6]
I tested this with one Seeedstudio Grove - Time of Flight Distance Sensor(VL53L0X).
The 'Grove Universal 4 Pin to Beaglebone Blue 4 Pin Female JST/SH Conversion Cable' allows an easy connection.
The Grove - I2C Hub also can be used.

Unfortunately the Grove sensor doesn't provide XSHUT/GPIO. So multi sensor or other features requiring XSHUT probably don't work with the Grove sensor.

Many thanks for the linux port and the nice code!

![img_0466](https://user-images.githubusercontent.com/43598967/46716606-03a97300-cc65-11e8-89ff-8bcd0d37aa7d.JPG)

**Comment by mjbogusz** [comment]
I've added the info to the readme, thanks!

It should be possible to use multiple sensors by soldering in additional 2.54 connector (2 pads on the side of Seeed's board) and wiring them to the BeagleBone or to a GPIO extender (even a latched shift register), though I have no way of verifying that.
You'd have to check the Eagle files (available here http://wiki.seeedstudio.com/Grove-Time_of_Flight_Distance_Sensor-VL53L0X/ ) and figure out which one is XSHUT and which is GPIO0. I'd guess the square one should be the XSHUT.

---

PS. Sorry about the commit/reference spam, I've had to figure out how to link an issue in the readme.
