### ISSUE TITLE
2 sensors

### ISSUE THREAD

**Issue by tiralonghipol** [mjbogusz/vl53l0x-linux#9]
Hi 
Thank you so much for sharing this!
I was able to stream one sensor correctly, even without connecting the xshut pin (default addess 0x29)
Now I would like to stream 2 vl53l0x with a raspberry pi 4
I am using pins 17 and 27 (wiPi 0 and 2) for the xshut.
Here is how I modified the continousMultipleSensors.cpp example:
```
	// Configuration constants
	// Number of sensors. If changed, make sure to adjust pins and addresses accordingly (ie to match size).
	const int SENSOR_COUNT = 2;
	// GPIO pins to use for sensors' XSHUT. As exported by WiringPi.
	const uint8_t pins[SENSOR_COUNT] = { 0, 2 };
	// Sensors' addresses that will be set and used. These have to be unique.
	const uint8_t addresses[SENSOR_COUNT] = {
		VL53L0X_ADDRESS_DEFAULT + 2,
		VL53L0X_ADDRESS_DEFAULT + 6
	};
```

I also notice that with this code, after calling 
```
sensors[i]->initialize();
```
if I check **$ i2cdetec -y 1** the output is (weird):
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
70: 70 71 72 73 74 75 76 77  
```

Also if instead I use the single.cpp with 2 sensors and I wave my hand in front of one of them one at a time, I get both measures (not sure in which order..)

What am I doing wrong? Can you help me somehow?
Hope I was clear

**Comment by mjbogusz** [comment]
The `i2cdetect` output seems very weird indeed, it should display `--` at all or almost all addresses.

After quick search I've found this very related SE post: https://raspberrypi.stackexchange.com/questions/32719/i2cdetect-shows-every-possible-address - make sure that `i2c1` is properly enabled (e.g. via `raspi-config`) and wired.

I can try verifying this behaviour on my RPi4, but AFAIR the last time I've checked I had `--` on all addresses but the used ones.

**Comment by tiralonghipol** [comment]
thank you for the reply
for some reason some gpio pins works (no weird behaviour on i2cdetect) and other do not
I tried both on 4gb and 8gb version of raspi4/b and I could not make it work properly
again one sensor works just fine, but with more than one the set of the address fails

**Comment by mjbogusz** [comment]
Can you share your wiring diagram?
Also, what type of a carrier board for the sensors are you using? Pololu, DFRobot, Adafruit, some custom one?

**Comment by tiralonghipol** [comment]
![20200803_151222](https://user-images.githubusercontent.com/26047078/89716222-19227d80-d960-11ea-8536-68e54478af9b.jpg)
I tried different gpio pins so they might be different from previous posted code
the sensor used is **[this one](https://www.amazon.com/DAOKI-Ranging-VL53L0X-Interface-Communication/dp/B082143FJJ/ref=sr_1_2_sspa?dchild=1&keywords=tof+sensor&qid=1596906978&sr=8-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyWDFJWU1XTzVGWDhDJmVuY3J5cHRlZElkPUEwNTgxNTQ1SEtMMUhLNDZQRVg5JmVuY3J5cHRlZEFkSWQ9QTA4MDkxNDkyQ1RSWDJVNEs3WEtLJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==)**

also with another python library I am able to stream both sensors at 30hz no problem

**Comment by mjbogusz** [comment]
On all the pictures of the board I've found the `SDA` and the `SCL` pins are the other way around compared to your sketch - could you check it?
Also, verify the resistance between I2C lines and ground, it should be very high or even open line - maybe something is shorting where it shouldn't and it pulls one of the lines down (in particular, the `SDA` data line).

Edit: are the GPIO files used by this library (https://github.com/mjbogusz/vl53l0x-linux/blob/master/VL53L0X.cpp#L496) valid on RPi4? AFAIR this was developed for BeagleBone, so the paths can be different.

**Comment by tiralonghipol** [comment]
Oh this is really helpful thank you!
I will check asap and come back to you

**Comment by tiralonghipol** [comment]
@mjbogusz 
thank you so much for your help
I just needed to change the file reference to access the gpio
I tried both on Raspberry pi4 and Khadas VIM3L, I confirm everything works perfectly
thank you again!
